// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4zSPGDSyipG7zlrkYrQptGqASdqBMQoQ',
    appId: '1:136792857610:web:f0990cca019c1daa7e93f3',
    messagingSenderId: '136792857610',
    projectId: 'auth-firebase-by-asadbek',
    authDomain: 'auth-firebase-by-asadbek.firebaseapp.com',
    storageBucket: 'auth-firebase-by-asadbek.firebasestorage.app',
    measurementId: 'G-18FFTD20SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQcwWAo0zdTtt_Drv9NVdAR53DZBkNsDA',
    appId: '1:136792857610:android:d40e2b5268b6fbcd7e93f3',
    messagingSenderId: '136792857610',
    projectId: 'auth-firebase-by-asadbek',
    storageBucket: 'auth-firebase-by-asadbek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5RqIf8lY-fgbnTOx0_d2nYsdiVOAL5s',
    appId: '1:136792857610:ios:dda8f131a39414a87e93f3',
    messagingSenderId: '136792857610',
    projectId: 'auth-firebase-by-asadbek',
    storageBucket: 'auth-firebase-by-asadbek.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirebaseAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5RqIf8lY-fgbnTOx0_d2nYsdiVOAL5s',
    appId: '1:136792857610:ios:dda8f131a39414a87e93f3',
    messagingSenderId: '136792857610',
    projectId: 'auth-firebase-by-asadbek',
    storageBucket: 'auth-firebase-by-asadbek.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirebaseAuthProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4zSPGDSyipG7zlrkYrQptGqASdqBMQoQ',
    appId: '1:136792857610:web:d53474cccdd920fc7e93f3',
    messagingSenderId: '136792857610',
    projectId: 'auth-firebase-by-asadbek',
    authDomain: 'auth-firebase-by-asadbek.firebaseapp.com',
    storageBucket: 'auth-firebase-by-asadbek.firebasestorage.app',
    measurementId: 'G-SMX6Q9WZRH',
  );
}
